# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OsirisjsonProducer < Formula
  desc "Generate private point-in-time infrastructure snapshots from hyperscalers, hosting and cloud providers and on-premises IT/OT systems as vendor-neutral OSIRIS JSON ready for reports, diagrams, audits, diffs, CMDB/IPAM/DCIM workflows and controlled AI/MCP context."
  homepage "https://osirisjson.org"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/osirisjson/osiris-producers/releases/download/v0.6.2/osiris-producers_0.6.2_darwin_amd64.tar.gz"
      sha256 "6ee9a4f7196cb058aa57f2ff038533684b58c1106c4042c819ab9b0f7c803eb2"

      define_method(:install) do
        bin.install "osirisjson-producer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/osirisjson/osiris-producers/releases/download/v0.6.2/osiris-producers_0.6.2_darwin_arm64.tar.gz"
      sha256 "dc55c28576bbf95fd85d97cddd1e6fcfc3905c07ddf079b8328d9af920c23deb"

      define_method(:install) do
        bin.install "osirisjson-producer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/osirisjson/osiris-producers/releases/download/v0.6.2/osiris-producers_0.6.2_linux_amd64.tar.gz"
      sha256 "9e17e18a770e2d2b0bac24bd8e637063a156c4c675be0a13601204beb9761c6c"
      define_method(:install) do
        bin.install "osirisjson-producer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/osirisjson/osiris-producers/releases/download/v0.6.2/osiris-producers_0.6.2_linux_arm64.tar.gz"
      sha256 "83138808c71d49e7c9cb7c934cc55a49cc4614e82feb5b48623808ab37213349"
      define_method(:install) do
        bin.install "osirisjson-producer"
      end
    end
  end

  test do
    system "#{bin}/osirisjson-producer", "--version"
  end
end
